#!/usr/bin/env bash

#Check for null or empty input

if [[ -z "$1" ]]; then
echo "Please enter a valid input."
echo "[+] Example: ./pingSweeper 192.168.1"
exit 1  # Exit with an error code
fi

#We need a 3 octect input , our program will not accept any other format

if [[ ! "$1" =~ ^([0-9]{1,3}[\.]){2}[0-9]{1,3}$ ]]; then
  echo "Error: Invalid IP address format. Please enter an IP address with only three octets (e.g., 192.178.1)."
  exit 1  # Exit with an error code

else
for ip in `seq 1 254` ; do
ping -c 1 $1.$ip |grep "64 bytes"|cut -d " " -f 4|tr -d ":" &
done
fi
